Bug 985656 - minor improvement for consistency in broker and console spec files
For some reason rhpkg really did not like the console spec's usage of
%{scl}-ruby-wrapper

Uploading: d79e6980b2997ea0f9b64fd2665f6d76  openshift-origin-console-1.5.22.tar.gz
error: line 32: Dependency tokens must begin with alpha-numeric, '_' or '/': Requires:      %{scl}-ruby-wrapper
error: query of specfile /home/bleanhar/git/rhpkg/openshift-origin-console/openshift-origin-console.spec failed, can't parse

Conflicts:

	openshift-console/openshift-origin-console.spec